services:
  database:
    extends:
      file: back/docker-compose.yaml
      service: database

  front: 
    extends:
      file: front/docker-compose.yaml
      service: node

  adminer:
    image: adminer:latest
    ports:
      - "9090:8080"

volumes:
  database_data:
