version: "3"

services:
  node:
    build: docker
    container_name: node
    stdin_open: true
    tty: true
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: /bin/sh -c "cd /app && pnpm install && pnpm dev"
